//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.22 at 09:54:22 AM BRT 
//


package br.com.totvs.tds.server.xml;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.totvs.tds.server.internal.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory implements IObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.totvs.tds.server.internal.xml
     * 
     */
    public ObjectFactory() {
    }

    /* (non-Javadoc)
	 * @see br.com.totvs.server.internal.xml.IObjectFactory#createGroup()
	 */
    @Override
	public Group createGroup() {
        return new Group();
    }

    /* (non-Javadoc)
	 * @see br.com.totvs.server.internal.xml.IObjectFactory#createGroupGroupList()
	 */
    @Override
	public Group.GroupList createGroupGroupList() {
        return new Group.GroupList();
    }

    /* (non-Javadoc)
	 * @see br.com.totvs.server.internal.xml.IObjectFactory#createServer()
	 */
    @Override
	public Server createServer() {
        return new Server();
    }

    /**
     * Create an instance of {@link XMLServerRoot }
     * 
     */
    public XMLServerRoot createXMLServerRoot() {
        return new XMLServerRoot();
    }

}
